component/Button/index.jsx, component/Typography/index.jsx
버튼 컴포넌트를 추가합니다
- height
- width
- backgroundColor
- color
- round
props 들을 받아 개발자가 유동적으로 디자인에 사용합니다
=> feat: add button component

.bebelrc, package-lock.json, package.json, pages/index.js, pages/login.js, yarn.lock
npm i babel-plugin-styled-components 플러그인 설치 후 .bebelrc 파일을 추가했습니다
=> feat: add babel & login page

component/Margin/index.jsx
Margin 기능을 가진 컴포넌트를 추가합니다
option 
- size
- row (boolean)
=> Margin 컴포넌트를 추가

.babelrc, pages/login.js, yarn.lock
.babelrc 파일 이름을 수정하여 Next.js Styled-Components ClassName 에러를 해결했습니다
=> .babelrc 파일 수정 및 에러 해결

pages/join.js, pages/login.js, yarn.lock
login과 join 페이지에서 state value를 변경했습니다
=> State 값 변경

component/Button/index.jsx, component/Input/index.jsx, pages/login.js
login 페이지 ux를 수정하고 next/link를 통해 회원가입 페이지과 연결했습니다.
하단에 '회원가입' 텍스르를 누르면 다음 페이지로 이동합니다
=> login 페이지 수정 및 link 연결

pages/index.js
시작 페이지에 main logo 아이콘을 추가했습니다.
=> 시작 페이지에 로고 추가

pages/index.js, pages/join.js, pages/login.js
1) 시작 페이지 로고 click 시 로그인 페이지로 넘어가도록 Link를 추가했습니다
2) type: password를 이용하여 비밀번호 비공개 처리 및 버튼과 텍스트 클릭 시 hover cursor pointer 처리를 추가했습니다
3) 혈액형 표기창에서 예시를 추가 작성했습니다. ex) A형 Rh+
=> 시작, 로그인, 회원가입 페이지 수정

pages/donorDetail.js, public/temp/temp-back.svg, public/temp/temp-card.svg, public/temp/temp-select.svg
1. 헌혈증 세부페이지를 제작하였습니다.
2. 아직 데이터를 받아오는 부분은 제외되어 있습니다.
3. 링크부분은 앵커로만 남겨둔 상태입니다.
=> 헌혈증 세부페이지 제작

package-lock.json, package.json, pages/camera.js, yarn.lock
react-qr-reader 라이브러리를 통해서 카메라로 QR코드 인식scan 기능을 추가했습니다.
(웹카메라는 기능 확인했고 PR올린 후에 previewURL로 모바일 카메라 test 예정)
useRef로 특정 DOM을 선택하고, useState로 컴포넌트에서 동적인 값 state를 관리합니다.
handleErrorCamera로 에러가 뜨면 console에 출력되고,
setScanResultCamera를 통해 결과를 set하고 QR코드가 인식scan되면,
location.href로 특정 페이지 (현재는 지훈이가 개발한 donorDetail 페이지로 설정)로 이동하도록 구현했습니다.
ReferenceError: Blob is not defined 에러를 해결하기 위해
camera 기능 구현을 위한 컴포넌트를 함수 안으로 넣으며
dynamic를 추가로 import했습니다
=> 카메라로 QR 코드 인식scan 기능 추가

pages/addAddress.js, pages/camera.js
addAddress 페이지를 추가했습니다.
textarea로 상대방 헌혈지갑 주소값을 입력 받으며, 입력 후에는 상세 페이지 donorDetail로 이동합니다.
앞서 구현한 camera 페이지 하단에 주소 입력하는 버튼에 Link 연결합니다.
=> 상대방 헌혈지갑 주소 입력 페이지 추가

package-lock.json, package.json, pages/addAddress.js, pages/camera.js, pages/donorDetail.js, pages/join.js, yarn.lock
페이지 이동을 위해 next/router의 useRouter을 import했습니다.
버튼에서 onClick 이벤트로 router.push을 통해 해당 link 페이지로 이동합니다
=> 전체 페이지에 useRouter 추가

pages/deliveryList.js, pages/login.js, public/temp/temp-back-white.svg
1. 로그인 페이지에 로고 애니메이션을 추가했습니다.
2. 헌혈증 전달내역 페이지 상단 바만 만들었습니다.
=> 로고 애니메이션 추가 & 헌혈증 전달 내역 페이지 상단 바만 추가

pages/join.js
=> 회원가입 api를 추가

pages/deliveryList.js
1. 하드 코딩했었던 전달 내역 페이지의 코드를 map을 이용하여 수정했습니다.
=> 전달내역 페이지 코드 map 사용해서 수정

pages/donorDetail.js
1. 헌혈증 상세보기 페이지에서 푸터바를 추가하였습니다.
2. 상단바의 텍스트부분 padding을 추가하였습니다.
=> 현혈증 상세보기 페이지 수정

pages/deliveryList.js
1. footer는 공용 컴포넌트로 교체했고
2. 헤더는 크기 맞췄습니다.
=> 전달내역 페이지 헤더&상단바 수정

pages/addAddress.js
addAddress 페이지 하단에 <Footer />를 추가하고 textarea를 수정했습니다
=> 주소 추가하는 페이지 uiux 수정

pages/deliveryList.js
1. 전달내역 페이지에서 뒤로가기 버튼을 누르면 헌혈 지갑으로 이동하도록 했습니다.
2. 전달 내역을 누르면 이더스캔 창을 새로 띄우도록 했습니다.
=> 전달 내역 페이지 수정(이더스캔, 뒤로가기 버튼)

component/Tutorial/index.jsx
1. tutorial page visible statusf를 통하여 문제를 해결하였습니다.
=> tutorial page 렌더 딜레이 조정

pages/addAddress.js, pages/camera.js
1. addAddress 페이지 css 껍데기만 조금 수정했습니다.
2. 입력 받은 데이터를 넘기는 작업은 안했습니다.
=> addAddress 페이지 CSS 약간 수정

component/Footer/index.jsx, pages/addAddress/[id].js, pages/deliveryList.js, pages/mywallet.js
=> Footer 포지션 하단에 고정

pages/donorDetail/[id].js
1. Donor detail 페이지 footer 고정시켰습니다.
=> Footer 포지션 하단에 고정(재수정)
